#!/usr/bin/env bash
# Installs Nginx with the following configurations:
#+    Listens on port 80.
#+    Returns a page containing "Hello World!" when queried
#++    at the root with a curl GET request.
# configures nginx server so that /redirect_me
#+ redirects to another page permanently(301)

sudo apt-get -y update
sudo apt-get install -y nginx

mkdir /etc/nginx/html
touch /etc/nginx/html/index.html
touch /etc/nginx/sites-available/new
mv /etc/nginx/sites-available/default /etc/nginx/sites-available/default.backup
rm /etc/nginx/sites-enabled/default
echo "Hello World!" > /etc/nginx/html/index.html
printf %s "server {
     listen      80 default_server;
     listen      [::]:80 default_server;
     root        /etc/nginx/html;
     index       index.html index.htm;

     location  /redirect_me {
     	return 301 https://github.com/matthiasVincent;
}
}
" > /etc/nginx/sites-available/new

ln -s /etc/nginx/sites-available/new /etc/nginx/sites-enabled/

sudo service nginx restart
