#!/usr/bin/env bash
# Installs Nginx with the following configurations:
#+    Listens on port 80.
#+    Returns a page containing "Hello World!" when queried
#++    at the root with a curl GET request# redirect permanently to another page when uri is /redirect_me

sudo apt-get -y update
sudo apt-get install -y nginx

mkdir /etc/nginx/html
touch /etc/nginx/html/index.html
touch /etc/nginx/html/404.html
echo "Hello World!" > /etc/nginx/html/index.html
echo "Ceci n'est pas une page" >/etc/nginx/html/404.html
printf %s "server {
     listen      80 default_server;
     listen      [::]:80 default_server;
     root        /etc/nginx/html;
     index       index.html index.htm;

     location   /redirect_me  {
          return 301 https://github.com/matthiasVincent;
  }
}
" > /etc/nginx/sites-available/default

ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/

sudo service nginx restart
