#!/usr/bin/env bash
# Installs Nginx with the following configurations:
#+    Listens on port 80.
#+    Returns a page containing "Hello World!" when queried
#++    at the root with a curl GET request.
# configures nginx server so that /redirect_me
#+ redirects to another page permanently(301)
# include a custom 404 error page containg "Ceci n'est pas une page"

sudo apt-get -y update
sudo apt-get install -y nginx

mkdir /etc/nginx/html
touch /etc/nginx/html/index.html
touch /etc/nginx/sites-available/new
mv /etc/nginx/sites-available/default /etc/nginx/sites-available/default.backup
rm /etc/nginx/sites-enabled/default
touch /etc/nginx/html/404.html
echo "Hello World!" > /etc/nginx/html/index.html
echo "Ceci n'est pas une page" > /etc/nginx/html/404.html
printf %s "server {
     listen      80 default_server;
     listen      [::]:80 default_server;
     root        /etc/nginx/html;
     index       index.html index.htm;

     error_page  404 /404.html;

     location  /redirect_me {
     	return 301 https://github.com/matthiasVincent;
}
     location /404 {
        root /etc/nginx/html;
	internal;
}
}
" > /etc/nginx/sites-available/new

ln -s /etc/nginx/sites-available/new /etc/nginx/sites-enabled/

sudo service nginx restart
